TILE_EMPTY = 8

-- WALL
TILE_WALL_TOP_LEFT = 97
TILE_WALL_TOP_MIDDLE = 103
TILE_WALL_TOP_RIGHT = 98
TILE_WALL_BOTTOM_LEFT = 99
TILE_WALL_BOTTOM_MIDDLE = 100
TILE_WALL_BOTTOM_RIGHT = 101
TILE_WALL_MIDDLE_LEFT = 104
TILE_WALL_MIDDLE_MIDDLE = 102
TILE_WALL_MIDDLE_RIGHT = 113

-- BORDER
TILE_BORDER_TOP_LEFT = 129
TILE_BORDER_TOP_MIDDLE = 132
TILE_BORDER_TOP_RIGHT = 118
TILE_BORDER_BOTTOM_LEFT = 116
TILE_BORDER_BOTTOM_RIGHT = 115
TILE_BORDER_LEFT = 130
TILE_BORDER_RIGHT = 119
TILE_BORDER_BOTTOM = 117

-- FLOOR
TILE_FLOOR_WOOD = 81
